### ISSUE TITLE
Cloud Detection dataset

### ISSUE THREAD

**Issue by SorourMo** [chrieke/awesome-satellite-imagery-datasets#10]
Hi,

First of all, thank you for preparing this awesome list of remote sensing datasets. It will help many researchers (like myself). May I know how I should add our own dataset (38-Cloud, a cloud segmentation dataset introduced by School of Engineering Science, Simon Fraser University, BC, Canada) to this list? 
Here is a link for this dataset: https://github.com/SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset

Thank you,
Sorour

**Comment by SorourMo** [comment]
Oh! My bad! This dataset has been already added! Sorry and thank you!

**Comment by SorourMo** [comment]
Oh! My bad! This dataset has been already added! Sorry and thank you!

**Comment by chrieke** [comment]
And thank you for publishing the dataset!

**Comment by SorourMo** [comment]
Hi there,

I just wanted to let you know that a new dataset for cloud detection in satellite imagery called "95-Cloud" (which is an extension to the "38-Cloud dataset" mentioned in this issue) has been lately released. Here is the link:
https://github.com/SorourMo/95-Cloud-An-Extension-to-38-Cloud-Dataset

Would you please considering adding this dataset to your invaluable list?

Cheers,
Sorour

**Comment by chrieke** [comment]
Thank you, added. Replaces the 38 cloud dataset entry.

**Comment by SorourMo** [comment]
Hello again!
I have an update about my previously listed dataset mentioned in this issue. The publication associated with the "95-Cloud: A Cloud Segmentation Dataset" has been changed. This paper has been recently published in IEEE JSTARS which is an open-access journal. So here is the updated link for the paper: [https://ieeexplore.ieee.org/document/9394710](https://ieeexplore.ieee.org/document/9394710). Could you please update the link in your list?
Thank you.

**Comment by chrieke** [comment]
Updated, thanks.
