### ISSUE TITLE
USBuildingFootprints

### ISSUE THREAD

**Issue by Melykuti** [chrieke/awesome-satellite-imagery-datasets#11]
Dear Christoph,

Thank you for curating this great resource! In addition to the Canadian building footprints, Microsoft also has an analogous USBuildingFootprints dataset (it's some 8 months earlier):
https://github.com/microsoft/USBuildingFootprints

Cheers,
Bence

**Comment by chrieke** [comment]
added, thank you.

**Comment by tumbleintoyourheart** [comment]
Hi @Melykuti,
While Microsoft only provides territories' geojson label masks, how can we achieve the training imageries?
