### ISSUE TITLE
Request to add Core3D dataset Links

### ISSUE THREAD

**Issue by GokulNC** [chrieke/awesome-satellite-imagery-datasets#12]
Hey, it's a great list of dataset sources! Thank you so much for that.

Please add this dataset too:  
https://spacenetchallenge.github.io/datasets/Core_3D_summary.html

**Comment by chrieke** [comment]
Hi, thanks for the suggestion. As this dataset provides no label data and is not a recent challenge I think it would be better not to include it in the list in order to keep the keep it focused. Hope you can understand this, if anyone objects please chime in. Thank you.
