### ISSUE TITLE
Request to add all datasets quoted here in FMoW

### ISSUE THREAD

**Issue by GokulNC** [chrieke/awesome-satellite-imagery-datasets#13]
Please check the Resources section in this link:
https://www.iarpa.gov/challenges/fmow.html#Resources

And kindly add all the listed datasets.

Also if possible, please add the list of all:
- free satellite image sources available like LandSat, Sentinel, Bhuvan, etc., along with the resolution of the sat, [etc](https://gisgeography.com/free-satellite-imagery-data-list/).
- free annotated maps data available like OpenStreetMaps, WikiMapia, etc.

Adding all these would make this awesome list more diverse :)

**Comment by chrieke** [comment]
Thanks for your suggestions, will add the RESISC45 dataset from the site. 
As for general satellite and geo data sources and specifications, imho I think it is best to keep this list focused on mostly "ready to use" datasets for ML&DL. Maybe someone else wants to chime in.
