### ISSUE TITLE
Cactus Aerial Photos

### ISSUE THREAD

**Issue by benmack** [chrieke/awesome-satellite-imagery-datasets#14]
- [**Cactus Aerial Photos**](https://www.kaggle.com/irvingvasquez/cactus-aerial-photos) *(J. Irving Vasquez-Gomez)*
\>16k Aerial photos of Cactus, used in [Aerial Cactus Identification Playground Challenge](https://www.kaggle.com/c/aerial-cactus-identification), Paper: [López-Jiménez et al. 2019](https://www.sciencedirect.com/science/article/pii/S1574954119300895?via%3Dihub), Kaggle kernels

**Comment by chrieke** [comment]
Added, thank you @benmack !
