### ISSUE TITLE
Large-scale Dataset for Instance Segmentation in Aerial Images

### ISSUE THREAD

**Issue by akshitac8** [chrieke/awesome-satellite-imagery-datasets#22]
Hi, Can you please add this dataset.
link: https://captain-whu.github.io/iSAID/dataset.html
development kit: https://github.com/CAPTAIN-WHU/iSAID_Devkit

**Comment by chrieke** [comment]
Hi @akshitac8, thanks for the suggestion. Could you give a few more details how this dataset is differentiated from DOTA? Categories seem to be the same & the text says the same imagery is used. Thank you!

**Comment by akshitac8** [comment]
The categories are the same as DOTA but the new dataset iSAID includes more detailed object-level annotations along with a segmentation mask.

**Comment by chrieke** [comment]
@akshitac8 Thanks for the infos, added iSAID and mention that it replace Dota in this list. Closing.
