### ISSUE TITLE
License info of datasets

### ISSUE THREAD

**Issue by ogencoglu** [chrieke/awesome-satellite-imagery-datasets#25]
Would be nice to have the license info of each dataset as well. Can be a text like _MIT_ or some icon next to each dataset.

**Comment by chrieke** [comment]
Cool idea, will try to add small icons soon.

**Comment by chrieke** [comment]
@ogencoglu Wanted to add these [badges](https://gist.github.com/lukas-h/2a5d00690736b4c3a7ba). But after looking into this, unfortunately most datasets don't make it easy to find the exact license type. Plus a badge would, for most people, probably be less informative than just mentioning outlier "not for commercial use" etc. in the text. So putting this off for now, thank you for the suggestion! Closing.

**Comment by ogencoglu** [comment]
Understandable. Thank you!
