### ISSUE TITLE
404 link

### ISSUE THREAD

**Issue by robmarkcole** [chrieke/awesome-satellite-imagery-datasets#28]
This link returns 404:

```
[**Agriculture-Vision Database & CVPR 2020 challenge**](https://www.agriculture-vision.com/dataset)
```

I setup an action to detect dead links on https://github.com/robmarkcole/satellite-image-deep-learning/blob/master/.github/workflows/action.yml

**Comment by chrieke** [comment]
Thanks @robmarkcole that is great! Fixed the link and copied your action!
