### ISSUE TITLE
May I ask if there is an object detection competetion for Satellite/Aerial image held in recently or in the next few month.

### ISSUE THREAD

**Issue by boringzly** [chrieke/awesome-satellite-imagery-datasets#3]
Good contribution. We want to take a competetion for Satellite image object detection in the next few month. So do you know if there is any competition that will be held in the next few month.

**Comment by chrieke** [comment]
The first two items on the list (OpenAI Tanzania and Airbus Ship Detection) should fit the bill. Other than that not that I know of. You can click the "Watch" button to get updated on any future changes to the list.
