### ISSUE TITLE
Add AFO dataset

### ISSUE THREAD

**Issue by Panicum** [chrieke/awesome-satellite-imagery-datasets#32]
Hi,

Check out [AFO dataset](https://www.kaggle.com/jangsienicajzkowy/afo-aerial-dataset-of-floating-objects).
This is a drone dataset of floating objects (people, boats, buoys, etc.), created to train maritime Search&Rescue object detectors. 
I think first of this type. 

Best regards,
Jan

**Comment by chrieke** [comment]
Thanks, adding it!
