### ISSUE TITLE
Please add the new LoveDA Dataset in your good summary.

### ISSUE THREAD

**Issue by Junjue-Wang** [chrieke/awesome-satellite-imagery-datasets#36]
We have released a new Domain Adaptive Semantic Segmentation dataset for land-cover classification (LoveDA).
Github Link: https://github.com/Junjue-Wang/LoveDA.
Paper is accepted by NeurIPS2021: [Paper Link](https://arxiv.org/abs/2110.08733)
This focuses on the domain difference between the rural and urban scenes.
The abstract of LoveDA is as follows:
`Deep learning approaches have shown promising results in remote sensing high spatial resolution (HSR) land-cover mapping. However, urban and rural scenes can show completely different geographical landscapes, and the inadequate generalizability of these algorithms hinders city-level or national-level mapping. Most of the existing HSR land-cover datasets mainly promote the research of learning semantic representation, thereby ignoring the model transferability. In this paper, we introduce the Land-cOVEr Domain Adaptive semantic segmentation (LoveDA) dataset to advance semantic and transferable learning. The LoveDA dataset contains 5927 HSR images with 166768 annotated objects from three different cities. Compared to the existing datasets, the LoveDA dataset encompasses two domains (urban and rural), which brings considerable challenges due to the:  1) multi-scale objects; 2) complex background samples; and 3) inconsistent class distributions. The LoveDA dataset is suitable for both land-cover semantic segmentation and unsupervised domain adaptation (UDA) tasks. Accordingly, we benchmarked the LoveDA dataset on eleven semantic segmentation methods and eight UDA methods. Some exploratory studies including multi-scale architectures and strategies, additional background supervision, and pseudo-label analysis were also carried out to address these challenges. `
### Highlights:

1. 5987 high spatial resolution (0.3 m) remote sensing images from Nanjing, Changzhou, and Wuhan
2. Focus on different geographical environments between Urban and Rural
3. Advance both semantic segmentation and domain adaptation tasks
4. Three considerable challenges:
    * Multi-scale objects
    * Complex background samples
    * Inconsistent class distributions

**Comment by chrieke** [comment]
Added, thanks!
