### ISSUE TITLE
Open AI Tanzania Data

### ISSUE THREAD

**Issue by DeepVoltaire** [chrieke/awesome-satellite-imagery-datasets#5]
Thanks for your great list!

The data of the Open AI Tanzania Challenge is available [here](https://docs.google.com/spreadsheets/d/1kHZo2KA0-VtCCcC5tL4N0SpyoxnvH7mLbybZIHZGTfE/edit#gid=0). They hid it pretty well in the competition description on Codalab [here](https://competitions.codalab.org/competitions/20100#participate).

**Comment by chrieke** [comment]
Thanks! Added both links, the data sheet is indeed hard to find. Good luck with the competition!
