### ISSUE TITLE
Not a real issue

### ISSUE THREAD

**Issue by HamzahNizami** [chrieke/awesome-satellite-imagery-datasets#8]
HI there, I'm sorry to use an issue like this, but I currently need your help with regards to this issue of yours. Is there any way to get in contact with you, maybe via email, in order to get help with this as I am currently facing this issue. 

Thanks in advance

https://github.com/facebookresearch/deepmask/issues/87#issue-205039007

**Comment by chrieke** [comment]
Please use the referenced issue thread.
