### ISSUE TITLE
Requirement of trees dataset

### ISSUE THREAD

**Issue by itsrrworld** [chrieke/awesome-satellite-imagery-datasets#9]
Hey, thank you for this repository you provided. This is really awesome repository and very useful too. Here i need some datasets ( image datasets ) for the purpose of **Classification of the types of trees** from satellite or UAV data. 

I found [this data](https://www.kaggle.com/c/planet-understanding-the-amazon-from-space/data) a bit useful, but this is only used for ***Cloud Cover Labels***

Can you please provide links for *classification of trees* too. It would be very helpful for me.

Thanks in advance :smile:

**Comment by chrieke** [comment]
Hi, there are 2 datasets on the list mentioning "tree species". You can also look into the Copernicus High-Resolution Layers Forest Type dataset. https://land.copernicus.eu/pan-european/high-resolution-layers/forests/forest-type-1

**Comment by blutjens** [comment]
Hi Ramesh, we have created an awesome-forests list of datasets for running ML algorithms on forests. The list contains not only includes satellite, but also UAV, cartographic, and lidar datasets: https://github.com/blutjens/awesome-forests. Feel free to add interesting datasets to the list. 

Note that the linked Copernicus dataset is a data _product_, so it does not contain ground-truth labels.
